Document: debhello
Title: Debian debhello Manual
Author: <insert document author here>
Abstract: This manual describes what debhello is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/debhello/debhello.sgml.gz

Format: postscript
Files: /usr/share/doc/debhello/debhello.ps.gz

Format: text
Files: /usr/share/doc/debhello/debhello.text.gz

Format: HTML
Index: /usr/share/doc/debhello/html/index.html
Files: /usr/share/doc/debhello/html/*.html
